# Generated by Django 3.1.7 on 2021-04-05 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_funcionario', models.CharField(max_length=150)),
                ('cpf_funcionario', models.CharField(max_length=14)),
                ('telefone_funcionario', models.CharField(max_length=14)),
                ('email_funcionario', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('sexo_funcionario', models.CharField(choices=[('feminino', 'feminino'), ('masculino', 'masculino')], max_length=20)),
                ('turno', models.CharField(max_length=15)),
                ('cargo', models.CharField(choices=[('camareira', 'camareira'), ('recepcionista', 'recepcionista')], default='', max_length=20)),
                ('ativo', models.CharField(choices=[('sim', 'sim'), ('não', 'não')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Hospede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=14)),
                ('telefone', models.CharField(max_length=14)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('sexo', models.CharField(choices=[('feminino', 'feminino'), ('masculino', 'masculino')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_quarto', models.PositiveIntegerField()),
                ('status_quarto', models.CharField(choices=[('ocupado', 'ocupado'), ('disponivel', 'disponivel')], max_length=20)),
                ('descricao', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, upload_to='pousada/media')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(default='', max_length=100)),
                ('data_entrada', models.DateTimeField()),
                ('data_saida', models.DateTimeField()),
                ('valor', models.FloatField()),
                ('status_reserva', models.CharField(choices=[('checkin', 'checkin'), ('checkout', 'checkout')], max_length=20)),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='pousada.hospede')),
                ('numero_quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pousada.quarto', verbose_name='Numero Quarto')),
            ],
        ),
    ]
